apiVersion: v1
imagePullSecrets:
- name: grafana-dev-dockercfg
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: grafana-dev-dockercfg
  name: grafana-dev
secrets:
- name: grafana-dev-dockercfg
